-- Roles and users schema for PLN UP2D CI
-- Run this on your MySQL/MariaDB database (adjust types if needed)

CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL UNIQUE,
  `description` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `role_id` INT DEFAULT NULL,
  `role` VARCHAR(100) DEFAULT NULL, -- denormalized for convenience
  `name` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed roles
INSERT IGNORE INTO roles (name, description) VALUES
('Admin', 'Administrator'),
('Operasi Sistem Distribusi', 'Operasi Sistem Distribusi'),
('Fasilitas Operasi', 'Fasilitas Operasi'),
('Pemeliharaan', 'Pemeliharaan'),
('K3L & KAM', 'K3L & KAM'),
('Perencanaan', 'Perencanaan');

-- Demo Perencanaan user (password: perencanaan123)
-- Hash of 'perencanaan123' using PHP password_hash default algo (bcrypt)
INSERT IGNORE INTO users (email, password, role, name)
VALUES ('perencanaan@pln.local', '$2y$10$wH6YQf1yGk4c8Qp0qW8/1e8k2b0xJQY5mQp0lH5zI7KfXx1aYfO8K', 'Perencanaan', 'Demo Perencanaan');

-- Example: add a demo admin user (commented out). This will NOT change existing Perencanaan user.
-- Replace the hashed password below with a password generated by your PHP environment (use password_hash()).
-- INSERT INTO users (email, password, role, name, role_id)
-- VALUES ('admin@pln.local', '<bcrypt-hash-here>', 'Admin', 'Demo Admin', (SELECT id FROM roles WHERE name = 'Admin'));
